services:
  frontend:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:?}
        VITE_APP_LOGIN_URL: ${VITE_APP_LOGIN_URL:?}
        VITE_LANDING_URL: ${VITE_LANDING_URL:?}
        VITE_GCP_API_KEY: ${VITE_GCP_API_KEY:?}
        VITE_TOKEN_REFRESH: ${VITE_TOKEN_REFRESH:?}
        VITE_SESSION_TIMEOUT: ${VITE_SESSION_TIMEOUT:?}
    ports:
      - 127.0.0.1:${VITE_FRONTEND_PORT:?VITE_FRONTEND_PORT is required}:80
    healthcheck:
      test: [CMD, wget, --quiet, --tries=1, --spider, http://127.0.0.1/]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 10s
    networks:
      - app-network
    restart: always
