"""iot baseline

Revision ID: 0001
Revises: 
Create Date: 2026-09-20 23:20:29.769893

"""
from typing import Sequence, Union

# Se importa sqlmodel para que se pueda usar en el script
import sqlmodel

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_type',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_device_type_code'),
    sa.UniqueConstraint('name', name='uq_device_type_name')
    )
    op.create_table('deviceoperation',
    sa.Column('time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_serial', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('operation_type', sa.Enum('SENSOR_DATA', 'KEEP_ACTIVE', 'SESSION_REQUEST', 'ERROR', 'OTHER', name='deviceoperationtype'), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', 'PENDING', name='deviceoperationstatus'), nullable=False),
    sa.PrimaryKeyConstraint('time', 'id')
    )
    op.create_index(op.f('ix_deviceoperation_operation_type'), 'deviceoperation', ['operation_type'], unique=False)
    op.create_table('environmenttype',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environmenttype_name'), 'environmenttype', ['name'], unique=False)
    op.create_table('identificationtype',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identificationtype_name'), 'identificationtype', ['name'], unique=True)
    op.create_table('locationcountry',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locationcountry_name'), 'locationcountry', ['name'], unique=False)
    op.create_table('locationstate',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['locationcountry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locationstate_name'), 'locationstate', ['name'], unique=False)
    op.create_table('locationcity',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['locationstate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locationcity_name'), 'locationcity', ['name'], unique=False)
    op.create_table('environment',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city_id', sa.Uuid(), nullable=False),
    sa.Column('type_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_public_map_visible', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['locationcity.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['environmenttype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('identification_type_id', sa.Uuid(), nullable=True),
    sa.Column('identification_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city_id', sa.Uuid(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('is_social_auth', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['locationcity.id'], ),
    sa.ForeignKeyConstraint(['identification_type_id'], ['identificationtype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_identification_number'), 'user', ['identification_number'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('device',
    sa.Column('serial', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('batch', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('firmware_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mac_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rssi', sa.Integer(), nullable=True),
    sa.Column('wifi_ssid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_reset_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gps_latitude', sa.Float(), nullable=True),
    sa.Column('gps_longitude', sa.Float(), nullable=True),
    sa.Column('gps_updated_at', sa.DateTime(), nullable=True),
    sa.Column('manufacture_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'PAIRED', 'ACTIVE', 'MAINTENANCE', 'UNPAIRED', name='devicestatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_connection', sa.DateTime(), nullable=True),
    sa.Column('broker_connected', sa.Boolean(), nullable=False),
    sa.Column('broker_connected_at', sa.DateTime(), nullable=True),
    sa.Column('broker_disconnected_at', sa.DateTime(), nullable=True),
    sa.Column('broker_status_updated_at', sa.DateTime(), nullable=True),
    sa.Column('environment_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_type_id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_type_id'], ['device_type.id'], ),
    sa.ForeignKeyConstraint(['environment_id'], ['environment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_device_type_id'), 'device', ['device_type_id'], unique=False)
    op.create_index(op.f('ix_device_serial'), 'device', ['serial'], unique=True)
    op.create_table('environmentinvitation',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('environment_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['environment.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('environmentuser',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('environment_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['environment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scoped_guest_invitation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope_type', sa.Enum('environment', 'device', name='scopetype'), nullable=False),
    sa.Column('scope_id', sa.Uuid(), nullable=False),
    sa.Column('access_starts_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', 'revoked', name='invitationstatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scoped_guest_invitation_email'), 'scoped_guest_invitation', ['email'], unique=False)
    op.create_index(op.f('ix_scoped_guest_invitation_owner_user_id'), 'scoped_guest_invitation', ['owner_user_id'], unique=False)
    op.create_index('ix_scoped_guest_invitation_scope', 'scoped_guest_invitation', ['scope_type', 'scope_id'], unique=False)
    op.create_index(op.f('ix_scoped_guest_invitation_scope_id'), 'scoped_guest_invitation', ['scope_id'], unique=False)
    op.create_index(op.f('ix_scoped_guest_invitation_scope_type'), 'scoped_guest_invitation', ['scope_type'], unique=False)
    op.create_table('scoped_guest_relation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('guest_user_id', sa.Uuid(), nullable=False),
    sa.Column('scope_type', sa.Enum('environment', 'device', name='scopetype'), nullable=False),
    sa.Column('scope_id', sa.Uuid(), nullable=False),
    sa.Column('access_starts_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['guest_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scoped_guest_relation_guest_user_id'), 'scoped_guest_relation', ['guest_user_id'], unique=False)
    op.create_index(op.f('ix_scoped_guest_relation_owner_user_id'), 'scoped_guest_relation', ['owner_user_id'], unique=False)
    op.create_index('ix_scoped_guest_relation_scope', 'scoped_guest_relation', ['scope_type', 'scope_id'], unique=False)
    op.create_index(op.f('ix_scoped_guest_relation_scope_id'), 'scoped_guest_relation', ['scope_id'], unique=False)
    op.create_index(op.f('ix_scoped_guest_relation_scope_type'), 'scoped_guest_relation', ['scope_type'], unique=False)
    op.create_index('uq_scoped_guest_relation_active_scope_guest', 'scoped_guest_relation', ['scope_type', 'scope_id', 'guest_user_id'], unique=True, postgresql_where=sa.text('is_active = true'), sqlite_where=sa.text('is_active = 1'))
    op.create_table('device_location_report',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('reported_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_location_report_device_id'), 'device_location_report', ['device_id'], unique=False)
    op.create_table('sensorreading',
    sa.Column('time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('device_serial', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('device_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('power_supply_state', sa.Boolean(), nullable=True),
    sa.Column('uptime', sa.Integer(), nullable=True),
    sa.Column('firmware_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reset_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('heap_free', sa.Integer(), nullable=True),
    sa.Column('wifi_rssi', sa.Integer(), nullable=True),
    sa.Column('wifi_ssid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('wifi_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('device_datetime', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('time', 'id')
    )
    op.create_index(op.f('ix_sensorreading_device_id'), 'sensorreading', ['device_id'], unique=False)
    op.create_index(op.f('ix_sensorreading_device_serial'), 'sensorreading', ['device_serial'], unique=False)
    op.execute(
        "SELECT create_hypertable('sensorreading', 'time', "
        "if_not_exists => TRUE, create_default_indexes => FALSE)"
    )
    op.execute(
        "SELECT create_hypertable('deviceoperation', 'time', "
        "if_not_exists => TRUE, create_default_indexes => FALSE)"
    )

    uid = "current_setting('app.current_user_id', true)"
    system = f"{uid} = ANY (ARRAY['system_mqtt', 'system_admin'])"
    member_environments = (
        "SELECT eu.environment_id FROM environmentuser eu "
        f"WHERE eu.user_id::text = {uid} AND {uid} <> '' AND eu.is_active = true"
    )
    guest_environments = (
        "SELECT sgr.scope_id FROM scoped_guest_relation sgr "
        f"WHERE sgr.scope_type = 'environment' AND sgr.guest_user_id::text = {uid} "
        f"AND sgr.is_active = true AND sgr.access_starts_at <= CURRENT_TIMESTAMP AND {uid} <> ''"
    )
    guest_devices = (
        "SELECT sgr.scope_id FROM scoped_guest_relation sgr "
        f"WHERE sgr.scope_type = 'device' AND sgr.guest_user_id::text = {uid} "
        f"AND sgr.is_active = true AND sgr.access_starts_at <= CURRENT_TIMESTAMP AND {uid} <> ''"
    )

    protected_tables = (
        "environment", "environmentuser", "device", "environmentinvitation",
        "scoped_guest_relation", "scoped_guest_invitation", "sensorreading",
        "deviceoperation", "device_location_report",
    )
    for table in protected_tables:
        op.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY')
        op.execute(f'ALTER TABLE "{table}" FORCE ROW LEVEL SECURITY')

    op.execute(f"""
        CREATE POLICY environment_member_access ON environment FOR ALL TO PUBLIC
        USING ({system} OR id IN ({member_environments}))
        WITH CHECK ({system} OR {uid} <> '')
    """)
    op.execute(f"""
        CREATE POLICY environment_guest_read ON environment FOR SELECT TO PUBLIC
        USING ({system} OR id IN ({guest_environments}) OR id IN (
            SELECT d.environment_id FROM device d
            WHERE d.id IN ({guest_devices}) AND d.environment_id IS NOT NULL
        ))
    """)
    op.execute(f"""
        CREATE POLICY environmentuser_member_access ON environmentuser FOR ALL TO PUBLIC
        USING ({system} OR (user_id::text = {uid} AND {uid} <> ''))
        WITH CHECK ({system} OR (user_id::text = {uid} AND {uid} <> ''))
    """)
    op.execute(f"""
        CREATE POLICY device_member_access ON device FOR ALL TO PUBLIC
        USING ({system} OR environment_id IN ({member_environments}))
        WITH CHECK ({system} OR environment_id IN ({member_environments}))
    """)
    op.execute(f"""
        CREATE POLICY device_guest_read ON device FOR SELECT TO PUBLIC
        USING ({system} OR environment_id IN ({guest_environments}) OR id IN ({guest_devices}))
    """)
    op.execute(f"""
        CREATE POLICY environmentinvitation_owner_access ON environmentinvitation FOR ALL TO PUBLIC
        USING ({system} OR owner_id::text = {uid})
        WITH CHECK ({system} OR owner_id::text = {uid})
    """)
    op.execute(f"""
        CREATE POLICY scoped_relation_access ON scoped_guest_relation FOR ALL TO PUBLIC
        USING ({system} OR owner_user_id::text = {uid} OR guest_user_id::text = {uid})
        WITH CHECK ({system} OR owner_user_id::text = {uid})
    """)
    op.execute(f"""
        CREATE POLICY scoped_invitation_access ON scoped_guest_invitation FOR ALL TO PUBLIC
        USING ({system} OR owner_user_id::text = {uid})
        WITH CHECK ({system} OR owner_user_id::text = {uid})
    """)
    for table in ("sensorreading", "device_location_report"):
        op.execute(f"""
            CREATE POLICY device_data_access ON {table} FOR SELECT TO PUBLIC
            USING ({system} OR device_id IN (
                SELECT d.id FROM device d
                WHERE d.environment_id IN ({member_environments})
                   OR d.environment_id IN ({guest_environments})
                   OR d.id IN ({guest_devices})
            ))
        """)
        op.execute(f"""
            CREATE POLICY device_data_system_write ON {table}
            FOR INSERT TO PUBLIC WITH CHECK ({system})
        """)
    op.execute(f"""
        CREATE POLICY operation_access ON deviceoperation FOR SELECT TO PUBLIC
        USING ({system} OR device_serial IN (
            SELECT d.serial FROM device d
            WHERE d.environment_id IN ({member_environments})
               OR d.environment_id IN ({guest_environments})
               OR d.id IN ({guest_devices})
        ))
    """)
    op.execute(f"""
        CREATE POLICY operation_system_write ON deviceoperation
        FOR INSERT TO PUBLIC WITH CHECK ({system})
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensorreading_device_serial'), table_name='sensorreading')
    op.drop_index(op.f('ix_sensorreading_device_id'), table_name='sensorreading')
    op.drop_table('sensorreading')
    op.drop_index(op.f('ix_device_location_report_device_id'), table_name='device_location_report')
    op.drop_table('device_location_report')
    op.drop_index('uq_scoped_guest_relation_active_scope_guest', table_name='scoped_guest_relation', postgresql_where=sa.text('is_active = true'), sqlite_where=sa.text('is_active = 1'))
    op.drop_index(op.f('ix_scoped_guest_relation_scope_type'), table_name='scoped_guest_relation')
    op.drop_index(op.f('ix_scoped_guest_relation_scope_id'), table_name='scoped_guest_relation')
    op.drop_index('ix_scoped_guest_relation_scope', table_name='scoped_guest_relation')
    op.drop_index(op.f('ix_scoped_guest_relation_owner_user_id'), table_name='scoped_guest_relation')
    op.drop_index(op.f('ix_scoped_guest_relation_guest_user_id'), table_name='scoped_guest_relation')
    op.drop_table('scoped_guest_relation')
    op.drop_index(op.f('ix_scoped_guest_invitation_scope_type'), table_name='scoped_guest_invitation')
    op.drop_index(op.f('ix_scoped_guest_invitation_scope_id'), table_name='scoped_guest_invitation')
    op.drop_index('ix_scoped_guest_invitation_scope', table_name='scoped_guest_invitation')
    op.drop_index(op.f('ix_scoped_guest_invitation_owner_user_id'), table_name='scoped_guest_invitation')
    op.drop_index(op.f('ix_scoped_guest_invitation_email'), table_name='scoped_guest_invitation')
    op.drop_table('scoped_guest_invitation')
    op.drop_table('environmentuser')
    op.drop_table('environmentinvitation')
    op.drop_index(op.f('ix_device_serial'), table_name='device')
    op.drop_index(op.f('ix_device_device_type_id'), table_name='device')
    op.drop_table('device')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_identification_number'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('environment')
    op.drop_index(op.f('ix_locationcity_name'), table_name='locationcity')
    op.drop_table('locationcity')
    op.drop_index(op.f('ix_locationstate_name'), table_name='locationstate')
    op.drop_table('locationstate')
    op.drop_index(op.f('ix_locationcountry_name'), table_name='locationcountry')
    op.drop_table('locationcountry')
    op.drop_index(op.f('ix_identificationtype_name'), table_name='identificationtype')
    op.drop_table('identificationtype')
    op.drop_index(op.f('ix_environmenttype_name'), table_name='environmenttype')
    op.drop_table('environmenttype')
    op.drop_index(op.f('ix_deviceoperation_operation_type'), table_name='deviceoperation')
    op.drop_table('deviceoperation')
    op.drop_table('device_type')
    # ### end Alembic commands ###
